spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/relex_chat
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres


  mail:
    host: smtp.gmail.com
    port: 465
    username: alina.scsh.28072002@gmail.com
    password: btcivtcceuamqufw
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
emailTemplate:
  verificationLink: http://localhost:8080/auth/verify


