
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/relex_chat
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: examplepassword
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
  security:
    jwt:
      secretKey: superDuper39Secret
      expiresMs:
        # 30 minutes
        accessToken: 1 800 000
        # in days
        refreshToken: 30

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html