
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/relex_chat
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres


  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: examplepassword
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html

emailTemplate:
  mainPage: https://www.musicman-vsu.online
  verificationLink: https://www.musicman-vsu.online/auth/verify